# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v1
        with:
          node-version: 16
         
      - name: install
        run: npm i
        
      - name: build
        run: npm run build
      - name: deploy
        run: |
              cp googlefc62804cfc44bb36.html docs/.vuepress/dist/
              cd docs/.vuepress/dist
              git config --global init.defaultBranch master
              git config --global user.email "shane-liang@outlook.com"
              git config --global user.name "shane-1"
              git init
              git add *
              git commit -m 'version 4.2'
              git push -f https://shane-1:${{ secrets.TOKEN }}@github.com/shane-1/shane-1.github.io.git master
              
      - name: edit
        run: git push -f https://shane-1:${{ secrets.TOKEN }}@github.com/shane-1/edit.git master

